local M = {}

function M.get()
	return {
		NormalFloat = { fg = C.current.fg, bg = C.current.bg },
		FloatBorder = { fg = C.current.fg, bg = C.current.bg },
		ColorColumn = { fg = C.current.none, bg = C.current.darkgray },
		Conceal = { fg = C.current.darkgray },
		Cursor = { fg = C.current.fg, bg = C.current.none, reverse = true },
		CursorIM = { fg = C.current.white, bg = C.current.none, reverse = true },
		Directory = { fg = C.current.blue, bg = C.current.none },
		EndOfBuffer = { fg = C.current.darkgray },
		ErrorMsg = { fg = C.current.none },
		Folded = { fg = C.current.gray, bg = C.current.none, italic = true },
		FoldColumn = { fg = C.current.blue },
		IncSearch = { fg = C.current.white, bg = C.current.blue },
		LineNr = { fg = C.current.gray },
		CursorLineNr = { fg = C.current.fg },
		MatchParen = { fg = C.current.yellow, bg = C.current.none, bold = true },
		ModeMsg = { fg = C.current.fg },
		MoreMsg = { fg = C.current.fg },
		NonText = { fg = C.current.darkgray },
		Pmenu = { fg = C.current.fg, bg = C.current.darkgray },
		PmenuSel = { fg = C.current.fg, bg = C.current.blue },
		PmenuSbar = { fg = C.current.fg, bg = C.current.darkgray },
		PmenuThumb = { fg = C.current.fg, bg = C.current.fg },
		Question = { fg = C.current.green },
		QuickFixLine = { fg = C.current.fg, bg = C.current.none, reverse = true },
		qfLineNr = { fg = C.current.fg, bg = C.current.none, reverse = true },
		Search = { fg = C.current.white, bg = C.current.blue },
		Substitute = { fg = C.current.black, bg = C.current.magenta },
		SpecialKey = { fg = C.current.cyan },
		SpellBad = { fg = C.current.red, bg = C.current.none, italic = true },
		SpellCap = { fg = C.current.blue, bg = C.current.none, italic = true },
		SpellLocal = { fg = C.current.cyan, bg = C.current.none, italic = true },
		SpellRare = { fg = C.current.cyan, bg = C.current.none, italic = true },
		StatusLine = { fg = C.current.fg, bg = C.current.darkgray },
		StatusLineNC = { fg = C.current.fg, bg = C.current.darkgray },
		StatusLineTerm = { fg = C.current.fg, bg = C.current.darkgray },
		StatusLineTermNC = { fg = C.current.fg, bg = C.current.darkgray },
		TabLineFill = { fg = C.current.fg, bg = C.current.none },
		TablineSel = { fg = C.current.darkgray, bg = C.current.cyan },
		Tabline = { fg = C.current.fg, bg = C.current.darkgray },
		Title = { fg = C.current.green, bg = C.current.none, bold = true },
		Visual = { fg = C.current.none, bg = C.current.darkgray },
		VisualNOS = { fg = C.current.none, bg = C.current.darkgray },
		WarningMsg = { fg = C.current.yellow },
		WildMenu = { fg = C.current.magenta, bg = C.current.none, bold = true },
		CursorColumn = { fg = C.current.none, bg = C.current.darkgray },
		CursorLine = { fg = C.current.none, bg = C.current.darkgray },
		ToolbarLine = { fg = C.current.fg, bg = C.current.darkgray },
		ToolbarButton = { fg = C.current.fg, bg = C.current.none, bold = true },
		NormalMode = { fg = C.current.fg, bg = C.current.none, reverse = true },
		InsertMode = { fg = C.current.green, bg = C.current.none, reverse = true },
		ReplacelMode = { fg = C.current.red, bg = C.current.none, reverse = true },
		VisualMode = { fg = C.current.cyan, bg = C.current.none, reverse = true },
		CommandMode = { fg = C.current.fg, bg = C.current.none, reverse = true },
		Warnings = { fg = C.current.yellow },
	}
end

return M
