local M = {}

function M.get()
	return {
		Normal = { fg = C.current.fg },
		NormalFloat = { fg = C.current.fg },
		Comment = { fg = C.current.gray, italic = true },
		Constant = { fg = C.current.orange },
		String = { fg = C.current.green },
		Character = { fg = C.current.green },
		Number = { fg = C.current.orange },
		Boolean = { fg = C.current.orange },
		Float = { fg = C.current.orange },
		Identifier = { fg = C.current.red },
		Function = { fg = C.current.blue },
		Statement = { fg = C.current.magenta },
		Conditional = { fg = C.current.magenta },
		Repeat = { fg = C.current.magenta },
		Label = { fg = C.current.magenta },
		Operator = { fg = C.current.cyan },
		Keyword = { fg = C.current.magenta },
		Exception = { fg = C.current.magenta },
		PreProc = { fg = C.current.yellow },
		Include = { fg = C.current.blue },
		Define = { fg = C.current.magenta },
		Macro = { fg = C.current.magenta },
		PreCondit = { fg = C.current.yellow },
		Type = { fg = C.current.yellow },
		StorageClass = { fg = C.current.yellow },
		Structure = { fg = C.current.yellow },
		Typedef = { fg = C.current.yellow },
		Special = { fg = C.current.blue },
		SpecialChar = { fg = C.current.orange },
		Tag = { fg = C.current.red },
		Delimiter = { fg = C.current.fg },
		SpecialComment = { fg = C.current.gray },
		Debug = { fg = C.current.red },
		Underlined = { underline = true },
		Ignore = { fg = C.current.gray },
		Error = { fg = C.current.white, bg = C.current.red },
		Todo = { fg = C.current.yellow, bold = true },
	}
end

return M
