local M = {}

function M.get()
	return {
		["@comment"] = { link = "Comment" },
		["@error"] = { link = "Error" },
		["@none"] = { fg = C.fg },
		["@preproc"] = { link = "PreProc" },
		["@define"] = { link = "Define" },
		["@operator"] = { link = "Operator" },
		["@punctuation.bracket"] = { fg = C.fg },
		["@punctuation.delimiter"] = { fg = C.fg },
		["@punctuation.special"] = { fg = C.blue },
		["@string"] = { link = "String" },
		["@string.regex"] = { fg = C.orange },
		["@string.escape"] = { fg = C.magenta },
		["@string.special"] = { fg = C.blue },
		["@character"] = { link = "Character" },
		["@character.special"] = { fg = C.magenta },
		["@boolean"] = { link = "Boolean" },
		["@number"] = { link = "Number" },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = C.blue },
		["@function.call"] = { fg = C.blue },
		["@function.macro"] = { fg = C.magenta },
		["@method"] = { fg = C.blue },
		["@method.call"] = { fg = C.blue },
		["@constructor"] = { fg = C.yellow },
		["@parameter"] = { fg = C.red },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { fg = C.magenta },
		["@keyword.operator"] = { fg = C.magenta },
		["@keyword.return"] = { fg = C.magenta },
		["@conditional"] = { link = "Conditional" },
		["@repeat"] = { link = "Repeat" },
		["@debug"] = { link = "Debug" },
		["@label"] = { link = "Label" },
		["@include"] = { link = "Include" },
		["@exception"] = { link = "Exception" },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = C.yellow },
		["@type.definition"] = { fg = C.yellow },
		["@type.qualifier"] = { fg = C.yellow },
		["@storageclass"] = { link = "StorageClass" },
		["@attribute"] = { fg = C.yellow },
		["@field"] = { fg = C.red },
		["@property"] = { fg = C.red },
		["@variable"] = { fg = C.red },
		["@variable.builtin"] = { fg = C.orange },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = C.orange },
		["@constant.macro"] = { fg = C.orange },
		["@namespace"] = { fg = C.yellow },
		["@symbol"] = { fg = C.orange },
		["@text"] = { fg = C.fg },
		["@text.strong"] = { bold = true },
		["@text.emphasis"] = { italic = true },
		["@text.underline"] = { underline = true },
		["@text.strike"] = { strikethrough = true },
		["@text.title"] = { fg = C.yellow, bold = true },
		["@text.literal"] = { fg = C.green },
		["@text.uri"] = { fg = C.blue, underline = true },
		["@text.math"] = { fg = C.blue },
		["@text.reference"] = { fg = C.blue },
		["@text.todo"] = { link = "Todo" },
		["@text.note"] = { fg = C.blue, bold = true },
		["@text.warning"] = { fg = C.yellow, bold = true },
		["@text.danger"] = { fg = C.red, bold = true },
		["@tag"] = { link = "Tag" },
		["@tag.attribute"] = { fg = C.yellow },
		["@tag.delimiter"] = { fg = C.fg },
	}
end

return M
